Repository HMOAA/HMOA_iOS, pull requests merged in 2023-03, with the labels that each got.

#19 [Feat] 검색 페이지 UI 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/Reactor/SearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchKeywordViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/Product.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchBarContainerView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchListTableViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultTopView.swift
Labels: UI

#20 [Feat] 검색 페이지 UI 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/Reactor/SearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchKeywordViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/Product.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchBarContainerView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchListTableViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultTopView.swift
Labels: UI

#23 [Refactor] ReactorKit 적용 및 VC수정
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Model/PwTextFieldState.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Reactor/LoginReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Reactor/RegisterReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/View/EmailCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewController/ChoiceEmailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewController/LoginViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewController/PwRegisterViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewController/RegisterViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewModel/ChocieEmailViewModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/ViewModel/PwRegisetrViewModel.swift
Labels: Refactoring

#27 [Feat] 몇 가지 UI 수정 & 페이지 삭제
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/HPeida.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/HPeida.imageset/Vector (7).svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/HPeidaSelected.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/HPeidaSelected.imageset/Vector (8).svg
  HMOA_iOS/HMOA_iOS/Source/Extenstions/Int++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UITabBarItem++Extensions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/AppTabbarController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/ViewController/HPediaViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/Reactor/CommentListReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/View/CommentListTopView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/ViewController/CommentListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentWrite/Reactor/CommentWriteReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentWrite/ViewController/CommentWriteViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/CommentCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/Reactor/SearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchKeywordViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/News/View/NewsCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/News/View/NewsCellFooterView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/News/View/NewsCellHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/News/View/NewsView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/News/ViewController/NewsViewController.swift
Labels: UI

#29 [Feat] 검색 페이지 기능 구현
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/Reactor/SearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/VIewController/SearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/View/SearchResultCollectionViewCell.swift
Labels: New Feature, UI

#31 [Feat] 댓글 정렬 기능 & 댓글 수정 기능 & 향수 하단 뷰 좋아요 기능 구현
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentDetail/Reactor/CommentDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentDetail/ViewController/CommentDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/Reactor/CommentListReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/ViewController/CommentListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentWrite/Reactor/CommentWriteReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentWrite/ViewController/CommentWriteViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Model/Comment.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Reactor/DetailViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/DetailBottomView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
Labels: New Feature, UI

#34 [Feat] 홈화면 UI 수정 및 헤더 뷰 Reactor 주입
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Model/HomeSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Model/Perfume.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeCellReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeHeaderReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeCellHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeFirstCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeFirstCellHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeTopCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
Labels: Refactoring, UI

#37 [Feat] 네트워킹 초기 작업
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Network/Address.swift
  HMOA_iOS/HMOA_iOS/Source/Network/ServiceAPI.swift
Labels: New Feature

#39 [Feat]LikeView UI 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIColor++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/AppTabbarController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Drawer/ViewController/DrawerViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Model/CardSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Model/LikeCardModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Model/LikeListModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Model/ListSecton.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Reactor/LikeReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/Reactor/TagReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/View/LikeCardCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/View/LikeListCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/View/TagCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/ViewController/LikeViewController.swift
Labels: UI

#42 [Feat] 브랜드 검색 & 상세 페이지 UI 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Model/BrandDetailSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Model/BrandInfo.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailCellReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailHeaderReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/ViewController/BrandDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/Model/Brand.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/Model/BrandSearchSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/Reactor/BrandSearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/VIewController/BrandSearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/View/BrandListCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/View/BrandListHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Reactor/DetailViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Model/Perfume.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Search/Reactor/SearchReactor.swift
Labels: UI

#48 [CleanUp] 불필요한 파일 제거
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/ViewController/ChoiceYearViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/ViewController/StartViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/ViewModel/ChoiceYearViewModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/ViewModel/StartViewModel.swift
Labels: Clean Up

#54 [Feat] 브랜드 상세 페이지 UI 추가 구현
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Model/BrandDetailSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailCellReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailHeaderReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/ViewController/BrandDetailViewController.swift
Labels: UI

#57 [Feat] 마이페이지 UI 수정
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/MyPage/rightArrow.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/MyPage/rightArrow.imageset/Vector (9).svg
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Model/MyPageSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Model/UserInfo.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/ViewController/MyLogViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyProfile/Viewcontroller/MyProfileViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OpenSource/ViewController/OpenSourceViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Policy/ViewController/PolicyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Version/ViewController/VersionViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/MyPageCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/MyPageSeparatorLineView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/MyPageTopView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/MyPageUserCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/MyPageView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: UI

#59 [Feat] 홈 화면 전체보기 페이지 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/ServiceAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/Reactor/BrandDetailCellReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeHeaderReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeFirstCellHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/TotalPerfume/Model/TotalPerfumeSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/TotalPerfume/Reactor/TotalPerfumeReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/TotalPerfume/ViewContorller/TotalPerfumeViewController.swift
Labels: New Feature, UI

#62 [UI] 연도 선택, Like페이지 UI 수정
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Reactor/ChoiceYearReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/ViewController/ChoiceYearViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/View/LikeCardCell.swift
Labels: UI
