Repository HMOAA/HMOA_iOS, pull requests merged in 2024-09, with the labels that each got.

#224 [Bug] 향BTI 1차 초반부 버그 등 해결
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Arrow Back.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/whiteBack.imageset/Arrow Back.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/whiteBack.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurveyResult/Reactor/HBTISurveyResultReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurveyResult/ViewController/HBTISurveyResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeTopCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
Labels: 🐞 Bug

#231 [UI] 가격대 및 향료 선택 화면
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteClearButton.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteClearButton.imageset/noteClearButton.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.imageset/noteXButton.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.svg
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINote/ViewController/HBTINoteViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Model/HBTIPerfumeSurveySection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Reactor/HBTIPerfumeSurveyReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTINoteCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTINoteQuestionCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/SupplementaryView/HBTINoteCategoryHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/ViewController/HBTIPerfumeSurveyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurvey/View/HBTISurveyQuestionCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurvey/ViewController/HBTISurveyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurveyResult/ViewController/HBTISurveyResultViewController.swift
Labels: 🎨 UI

#233 [UI] 향수 매칭 결과 화면 컴포넌트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIColor++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Model/HBTIPerfumeResultSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Reactor/HBTIPerfumeResultReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/View/HBTIPerfumeResultCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
Labels: 🎨 UI

#214 [UI] 향BTI 수량 선택 화면 컴포넌트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/Model/HBTIQuantitySelectData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/Model/ReuseIdentifying.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/View/HBTIQuantitySelectButton.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/View/HBTIQuantitySelectCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/View/HBTIQuantitySelectTopView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/ViewController/HBTIQuantitySelectViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
Labels: 🎨 UI

#221 [UI] 향BTI 향료 카테고리 선택 결과 화면 컴포넌트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/Model/HBTINotesResultModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/Model/ReuseIdentifying.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/View/HBTINotesResultCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/View/HBTINotesResultFooterView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/View/HBTINotesResultHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/ViewController/HBTINotesResultViewController.swift
Labels: 🎨 UI

#236 [New Feature] 가격대 및 향료 선택화면 상호작용
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Model/HBTIPerfumeSurveySection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Reactor/HBTIPerfumeSurveyReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTINoteQuestionCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/ViewController/HBTIPerfumeSurveyViewController.swift
Labels: ✨ New Feature, 🎨 UI

#241 [New Feature] 향BTI 2차 네트워킹
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAddress.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Reactor/HBTIPerfumeResultReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/View/HBTIPerfumeResultCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Reactor/HBTIPerfumeSurveyReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/ViewController/HBTIPerfumeSurveyViewController.swift
Labels: ✨ New Feature

#244 [Fetch] 향BTI 2차
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteClearButton.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteClearButton.imageset/noteClearButton.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.imageset/noteXButton.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/noteXButton.svg
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIColor++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAddress.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINote/Reactor/HBTINoteReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINote/ViewController/HBTINoteViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Model/HBTIPerfumeResultSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Model/ResultPriority.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Reactor/HBTIPerfumeResultReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/View/HBTIPerfumeResultCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Model/HBTIPerfumeSurveySection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Reactor/HBTIPerfumeSurveyReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTINoteCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTINoteQuestionCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/HBTISelectedNoteView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/View/SupplementaryView/HBTINoteCategoryHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/ViewController/HBTIPerfumeSurveyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurvey/View/HBTISurveyQuestionCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurvey/ViewController/HBTISurveyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTISurveyResult/ViewController/HBTISurveyResultViewController.swift
Labels: 🏎️ Fetch

#246 [UI] 주문내역 UI 컴포넌트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Model/OrderLogSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Reactor/OrderLogReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCategoryView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/ViewController/OrderLogViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🎨 UI

#250 [UI] 취소/반품 상세화면 컴포넌트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/Int++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderCancelDetail/Reactor/OrderCancelDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderCancelDetail/View/OrderCancelCategoryView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderCancelDetail/View/ProductPriceView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderCancelDetail/ViewController/OrderCancelDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/ViewController/OrderLogViewController.swift
Labels: 🎨 UI

#245 [New Feature] 향료 수량 선택 화면 상호작용
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/Model/HBTINotesCategoryData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/Reactor/HBTINotesCategoryReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/ViewController/HBTINotesCategoryViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/View/HBTINotesResultHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIProcessGuide/Model/HBTIProcessGuideMessage.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIProcessGuide/ViewController/HBTIProcessGuideViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/Model/HBTIQuantitySelectData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/Reactor/HBTIQuantitySelectReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/View/HBTIQuantitySelectCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIQuantitySelect/ViewController/HBTIQuantitySelectViewController.swift
Labels: ✨ New Feature
