Repository HMOAA/HMOA_iOS, pull requests merged in 2024-11, with the labels that each got.

#303 [New Feature] 주문내역에서 후기 작성
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Member/Model/Member.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/Common/View/HBTIReviewView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Model/OrderLogSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Reactor/OrderLogReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCategoryView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/ViewController/OrderLogViewController.swift
Labels: ✨ New Feature, 🎨 UI

#299 [UI] 홈 화면 배너 이미지 가공
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeTopCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeView.swift
Labels: 🎨 UI

#296 [Refactoring] 닉네임 중복 체크 방식 변경
  HMOA_iOS/HMOA_iOS/Source/Network/API/Member/MemberAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Login/Start/Reactor/NicknameReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIReviewList/ViewController/HBTIReviewListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyProfile/Reactor/ChangeProfileImageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyProfile/Viewcontroller/ChangeProfileImageViewController.swift
Labels: ♻️ Refactoring

#302 [Refactor] 매거진 상세화면 리팩토링
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/Reactor/MagazineDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/View/MagazineLikeCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/ViewController/MagazineDetailViewController.swift
Labels: ♻️ Refactoring

#310 [Bug] 향BTI 1차 주문서 페이지의 백버튼 버그
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/ViewController/HBTINotesCategoryViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/ViewController/HBTINotesResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/ViewController/HBTIOrderSheetViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIProcessGuide/ViewController/HBTIProcessGuideViewController.swift
Labels: 🐞 Bug

#313 [Refactor] 향료 카테고리 페이지 리팩토링
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Aqua.imageset/Aqua.png
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Aqua.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Citrus.imageset/Citrus.png
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Citrus.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Floral.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Floral.imageset/Floral.png
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Fruit.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Fruit.imageset/Fruit.png
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Green.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Green.imageset/Green.jpeg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Musk.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Musk.imageset/Musk.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Spice.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Spice.imageset/Spice.png
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Sweet.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Sweet.imageset/Sweet.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Woody.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/HBTI/Notes/Woody.imageset/Woody.jpeg
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAddress.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/Model/HBTINotesCategoryData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/Reactor/HBTINotesCategoryReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/View/HBTINotesCategoryButton.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/View/HBTINotesCategoryCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/View/HBTINotesCategoryHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/View/HBTINotesCategoryTopView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/ViewController/HBTINotesCategoryViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/View/HBTIProductInfoCell.swift
Labels: ♻️ Refactoring

#312 [Bug] 홈에서 향BTI 버튼 탭 버그
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/HBTIAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/HBTI/Model/HBTIModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Model/ResultPriority.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/Reactor/HBTIPerfumeResultReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/Reactor/HBTIPerfumeSurveyReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeSurvey/ViewController/HBTIPerfumeSurveyViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/Podfile.lock
Labels: 🐞 Bug

#316 [UI] 환불이후 환불완료 팝업창 추가
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Comon/View/AlertType.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Comon/View/AlertViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTI/ViewController/HBTIViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIReviewList/ViewController/HBTIReviewListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderCancelDetail/ViewController/OrderCancelDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Reactor/OrderLogReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/ViewController/OrderLogViewController.swift
Labels: 🐞 Bug, ✨ New Feature, ♻️ Refactoring, 🎨 UI

#327 [UI] 가격대 우선시 향수 없을때 안내 화면 추가
  HMOA_iOS/HMOA_iOS/Source/Presentation/Comon/View/IconMessageView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
Labels: ♻️ Refactoring, 🎨 UI

#331 [UI] 브랜드 이미지 삭제
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Network/API/Detail/Model/FirstDetail.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/ViewController/BrandDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Reactor/DetailViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/BrandView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/Podfile.lock
Labels: 🧹Clean Up, 🎨 UI

#328 [UI] 브랜드 목록의 컬렉션뷰 수정
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/Model/Brand.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/Reactor/BrandSearchReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/VIewController/BrandSearchViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/View/BrandListCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandSearch/View/BrandListHeaderView.swift
Labels: 🧹Clean Up, ♻️ Refactoring, 🎨 UI

#330 [UI] 향BTI 이벤트 내용 문구 추가
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/View/HomeTopCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/Model/OrderLogSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/View/OrderCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/OrderLog/ViewController/OrderLogViewController.swift
Labels: 🐞 Bug, 🎨 UI

#332 [New Feature] 주문서 페이지 기능 추가 및 향BTI 1차 후반부문구 수정
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIAddFixAdress/Reactor/HBTIAddFixReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIAddFixAdress/ViewController/HBTIAddFixAddressViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/Model/HBTINotesCategoryData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesCategory/ViewController/HBTINotesCategoryViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTINotesResult/ViewController/HBTINotesResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/Reactor/HBTIOrderReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/View/HBTIProductInfoView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/ViewController/HBTIOrderResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIOrderSheet/ViewController/HBTIOrderSheetViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIPerfumeResult/ViewController/HBTIPerfumeResultViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIProcessGuide/Model/HBTIProcessGuideMessage.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/HBTI/HBTIProcessGuide/ViewController/HBTIProcessGuideViewController.swift
  HMOA_iOS/Podfile.lock
Labels: 🐞 Bug, ✨ New Feature, 🎨 UI
