Repository HMOAA/HMOA_iOS, pull requests merged in 2024-05, with the labels that each got.

#151 [Feat] 매거진 탭 기능 구현
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/magazineSelected.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/magazineSelected.imageset/fill.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Tabbar/magazineSelected.imageset/state-layer.png
  HMOA_iOS/HMOA_iOS/Source/Extenstions/Notification++Extensions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UILabel++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Magazine/MagazineAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Magazine/MagazineAddress.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Magazine/Model/MagazineModel.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Comon/View/SupplementaryViewKind.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Model/MagazineItem.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Reactor/MagazineReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/MagazineAllCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/MagazineMainCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/MagazineNewPerfumeCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/MagazineTopReviewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/Supplementary View/BackgroundDecorationView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/View/Supplementary View/MagazineHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/Model/MagazineDetailItem.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/View/ContentsCell/MagazineContentCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/View/MagazineInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/View/MagazineLikeCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/View/MagazineListCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/MagazineDetail/ViewController/MagazineDetailViewController.swift
Labels: ✨ New Feature, 🎨 UI

#152 [Bug] Bug 수정, UI 수정 사항 반영
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/emptyHeart.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/emptyHeart.imageset/line.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/heart.imageset/Vector.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/heart.imageset/fill.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/heart_fill.imageset/Vector.svg
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/like.imageset/Contents.json
  HMOA_iOS/HMOA_iOS/Resource/Assets.xcassets/Home/Detail/like.imageset/Frame 58.svg
  HMOA_iOS/HMOA_iOS/Resource/GoogleService-Info.plist
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIButton++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Login/AppRequestInterCeptor.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Member/MemberAPI.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Member/MemberAddress.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityDetail/Reactor/CommunityDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityDetail/View/CommunityPostCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityDetail/ViewController/CommunityDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityList/Service/CommunityListService.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityWrite/ViewController/CommunityWriteViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/View/HPediaQnACell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/Option/Model/OptionData.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/Option/View/OptionView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/BrandDetail/View/BrandDetailCollectionViewCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentDetail/Reactor/CommentDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentDetail/ViewController/CommentDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/Reactor/CommentListReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentList/ViewController/CommentListViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/CommentWrite/Reactor/CommentWriteReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Reactor/DetailViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/Service/DetailCommentService.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/CommentCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/CommentHeaderView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/DetailView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/ViewController/DetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/Reactor/HomeViewReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Like/ViewController/LikeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/Reactor/MyLogCommentReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/ViewController/MyLogCommentViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/View/NoLoginView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
  HMOA_iOS/Podfile.lock
Labels: 🐞 Bug, ✨ New Feature, 🎨 UI

#154 Hmoa 153/bug/comment my page
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityDetail/Reactor/CommunityDetailReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/CommunityDetail/ViewController/CommunityDetailViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/CommentCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/Model/MyLogCommentSection.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/Reactor/MyLogCommentReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/ViewController/MyLogCommentViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/ViewController/MyLogViewController.swift
Labels: 🐞 Bug

#156 [Config] 버전 업데이트 및 Podfile업데이트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/xcshareddata/xcschemes/HMOA_iOS.xcscheme
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/Reactor/MyLogCommentReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/MyLog/ViewController/MyLogCommentViewController.swift
  HMOA_iOS/Podfile.lock
Labels: ⚒️ Project Setup

#160 [Feat] 추가적인 업데이트 사항
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/ViewController/HPediaViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ New Feature

#163 [Bug] 1.0.4 버전 버그 수정
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UITabBarItem++Extensions.swift
  HMOA_iOS/HMOA_iOS/Source/Manager/LoginManager.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/AppTabbarController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/Reactor/HPediaReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/ViewController/HPediaViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
Labels: 🐞 Bug

#168 [UI] 매거진 UI 관련 업데이트
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
Labels: 🎨 UI

#167 [Refactor] 향수 상세 정보 DTO 변경에 따른 변경사항 수정
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/xcshareddata/xcschemes/HMOA_iOS.xcscheme
  HMOA_iOS/HMOA_iOS/Source/Network/API/Detail/Model/FirstDetail.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/DetailView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/Podfile
  HMOA_iOS/Podfile.lock
Labels: ✨ New Feature, ♻️ Refactoring

#169 [Bug] 매거진 버그 수정
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Reactor/MagazineReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/Podfile.lock
Labels: 🐞 Bug

#172 [Fetch] Hmoa 158/release/1.0.5
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS.xcodeproj/xcshareddata/xcschemes/HMOA_iOS.xcscheme
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UITabBarItem++Extensions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Manager/LoginManager.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Detail/Model/FirstDetail.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/AppTabbarController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/Reactor/HPediaReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/ViewController/HPediaViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/DetailView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Reactor/MagazineReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
  HMOA_iOS/Podfile
  HMOA_iOS/Podfile.lock
Labels: 🏎️ Fetch

#173 [Release] 1.0.5 업데이트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS.xcodeproj/xcshareddata/xcschemes/HMOA_iOS.xcscheme
  HMOA_iOS/HMOA_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UITabBarItem++Extensions.swift
  HMOA_iOS/HMOA_iOS/Source/Extenstions/UIViewController++Extenstions.swift
  HMOA_iOS/HMOA_iOS/Source/Manager/LoginManager.swift
  HMOA_iOS/HMOA_iOS/Source/Network/API/Detail/Model/FirstDetail.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/AppTabbarController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/Reactor/HPediaReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/HPedia/HPedia/ViewController/HPediaViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/DetailView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoCell.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Detail/View/PerfumeInfoView.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Reactor/MagazineReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/Magazine/Magazine/Viewcontroller/MagazineViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/Reactor/MyPageReactor.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
  HMOA_iOS/Podfile
  HMOA_iOS/Podfile.lock
Labels: 📦 Release

#175 [Bug] 로그아웃 버그 해결
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Manager/LoginManager.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🐞 Bug

#176 [Release] 1.0.6 업데이트
  HMOA_iOS/HMOA_iOS.xcodeproj/project.pbxproj
  HMOA_iOS/HMOA_iOS/Source/Manager/LoginManager.swift
  HMOA_iOS/HMOA_iOS/Source/Presentation/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: 📦 Release
